### ISSUE TITLE
Unstyled menu when no primary is selected

### ISSUE THREAD

**Issue by flashadvocate** [ncstate/wordpress-template#9]
Brian (DeConinck) already brought this up, but the default menu (before a primary menu is created / saved) doesn't get any of the style rules intended for `#global-nav`, likely because of the container div that is generated, stumping the child selectors.

I was able to correct this by dropping the child selector for the initial ul, and also adding an active state rule for `.current_page_item`

Obviously this will cease to be a problem when the user sets up their menu, with submenus and whatnot (and also since you cover it in the readme as one of the steps), but that initial styling may throw people off. This just serves to avoid any wasteful support queues.

~~Created a PR for this issue~~
Redid the PR for this issue

**Comment by flashadvocate** [comment]
Forgive the mess, I overlooked the SCSS templates

**Comment by csthomp89** [comment]
Thanks for the PR! That had been confusing for some users (who reads documentation?), so this will be a nice improvement.
